name: 매일 오전 8시 Firebase 전체 데이터 초기화

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Firebase Admin SDK로 DB 삭제 및 외식모드 초기화
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json

          npm init -y
          npm install firebase-admin

          node <<EOF
          const admin = require("firebase-admin");
          const serviceAccount = require("./serviceAccountKey.json");

          admin.initializeApp({
            credential: admin.credential.cert(serviceAccount),
            databaseURL: process.env.FIREBASE_DATABASE_URL
          });

          const db = admin.database();

          async function resetDatabase() {
            try {
              await db.ref().remove();
              console.log("전체 데이터 삭제 완료");

              await db.ref("settings/externalMode").set(false);
              console.log("외식모드 초기화 완료");

              process.exit(0);
            } catch (err) {
              console.error("초기화 실패", err);
              process.exit(1);
            }
          }

          resetDatabase();
          EOF
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
